export const COMMANDS = {
  up: "up",
  cd: "cd",
  ls: "ls",
  cat: "cat",
  add: "add",
  rn: "rn",
  cp: "cp",
  mv: "mv",
  rm: "rm",
  hash: "hash",
  os: "os",
  compress: "compress",
  decompress: "decompress",
  exit: ".exit",
};
